### ISSUE TITLE
Prebuild policy, without the need to install the SELinux toolchain

### ISSUE THREAD

**Issue by zvonkok** [NVIDIA/dgx-selinux#2]
Can we include a prebuild policy (the .pp file) as a release/download, so others can use the policy right away without installing SELinux toolchain?

**Comment by NewtonLiuNVIDIA** [comment]
Good idea, we'll include our current build in the project (again with the disclaimer that it's only been validated against a DGX Server)

**Comment by jamieNguyenNVIDIA** [comment]
Done!

Closed by: 45f1bae880dd205da26fcd9cf0bdde5cff95d13f
